
DEFAULT = 7
GREEN   = 2
YELLOW  = 3
TEAL    = 6
RED     = 1
PURP    = 5

TPUT	=	tput setaf

SET_DEFAULT = $(TPUT) $(DEFAULT)
SET_GREEN   = $(TPUT) $(GREEN)
SET_YELLOW  = $(TPUT) $(YELLOW)
SET_TEAL    = $(TPUT) $(TEAL)
SET_RED     = $(TPUT) $(RED)
SET_PURP    = $(TPUT) $(PURP)

ECHO	=	echo

COLOR_DEFAULT	= $$($(SET_DEFAULT))
COLOR_GREEN		= $$($(SET_GREEN))
COLOR_YELLOW	= $$($(SET_YELLOW))
COLOR_TEAL		= $$($(SET_TEAL))
COLOR_RED		= $$($(SET_RED))
COLOR_PURP		= $$($(SET_PURP))
