version: 2.1

executors:
  kernel-build-tools:
    docker:
      - image: jadomage/kernel-build-tools:latest
    environment:
      - TERM=xterm
jobs:

  build:
    executor: kernel-build-tools
    steps:
      - checkout
      - run: tools/create_build_dir i386
      - run: make -C build/i386
      - store_artifacts:
          path: build

  hosted_tests:
    executor: kernel-build-tools
    steps:
      - run: make -C build/i386 test

workflows:
  version: 2
  Pipeline:
    jobs:
      - build
